language: go

go:
  - "1.11"


before_install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - find . -type f -iname '*.go' -exec sed -i 's/github.com\/tendermint\/tendermint/github.com\/iov-one\/tendermint/g' {} +
  - dep ensure
  - CGO_ENABLED=0 go build -tags tendermint -o DOCKER/tendermint ./cmd/tendermint/

after_success:
  - version=$(awk -F\" '/TMCoreSemVer =/ { print $2; exit }' < ./version/version.go)
  - echo $version
  - docker build -t "iov1/tendermint:$version" DOCKER/
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "iov1/tendermint:$version"
  - docker logout


branches:
  only:
  - master

notifications:
  email: false
